### ISSUE TITLE
Retornar os valores de um json com chaves em maiúsculo

### ISSUE THREAD

**Issue by lucalves** [mahenrique94/requisicao-http#1]
Boa tarde,

O parabenizo pela criação do exemplo fazendo o consumo da requisição web service de forma nativa. Estou utilizando e testando com alguns projetos, porém me deparei com a seguinte questão:

Estou tentando ler os valores de um Json, que está com as chaves em maiúsculo. E o exemplo, só puxa os valores de chaves com Json em maiúsculo, como eu poderia fazer isto? Um exemplo, dentro da api webservice está com os seguintes valores:

`{"_classname":"PRODUTOS","CODBAR":"7894174238207","CODIGO":"580000109","DESCRICAO":"ADESIVO SELANTE 400G TRANSP FIXATUDO QUARTZOLIT","ESTOQCD":48,"ESTOQGER":98,"ESTOQLJ":0,"PRCPROD":0,"STATUS":"Nao","UM":"UN"}`

Como eu faço, diante do seu exemplo pra conseguir puxar os valores desta api, que tem as chaves do Json em maiúsculas? Eu teria que converter ou há uma forma de fazer isto diretamente via Gson?

No aguardo! Desde já agradeço.

**Comment by mahenrique94** [comment]
Fala ai Lucas, obrigado.

Bom, eu não mexo mais com Android, mas, acredito que talvez você vai precisar criar uma classe só para fazer esse *parse* através do Gson, os atributos da classe devem ser iguais ao JSON, ou seja, em maiusculo.

Acredito que tem boas chances de dar certo.

Abraços.

**Comment by lucalves** [comment]
Tudo bem,

Obrigado!
